home/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.home, name="home"),
    path('index/', views.index, name="index"),
    
    path('tiem/', views.tiem, name="tiem"),
    path('add_tiem/', views.add_tiem, name="add_tiem"),
    path('edit_tiem/<int:id>/', views.edit_tiem, name="edit_tiem"),
    path('delete_tiem/<int:id>/', views.delete_tiem, name="delete_tiem"),
    
    path('add_benh/', views.add_benh, name="add_benh"),
    path('add_benhtiem/', views.add_benhtiem, name="add_benhtiem"),
    path('add_vacxin/', views.add_vacxin, name="add_vacxin"),

    path('tk/', views.tk, name="tk"),
    path('register/', views.register, name="register"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    # path('change_mk/', views.change_mk, name="change_mk"),

    path('add_tn/', views.add_tn, name="add_tn"),
    path('edit_tn/<int:id>/', views.edit_tn, name="edit_tn"),
    path('delete_tn/<int:id>/', views.delete_tn, name="delete_tn"),

    path('health/<int:id>/', views.health, name="health"),
    path('add_health/<int:id>/', views.add_health, name="add_health"), 
    path('edit_health/<int:id_per>/<int:id_health>/', views.edit_health, name="edit_health"),
    path('delete_health/<int:id_per>/<int:id_health>/', views.delete_health, name="delete_health"),

    path('detail_health/<int:id>/', views.detail_health, name="detail_health"),

    path('tk_benh/', views.tk_benh, name="tk_benh"),
    path('tk_tiem/', views.tk_tiem, name="tk_tiem"),

    # path('add_thuoc/', views.add_thuoc, name="add_thuoc"),
] 

web/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

SHIRT_SIZES = [
        ("0", "admin"),
        ("1", "Ông"),
        ("2", "Bà"),
        ("3", "Cha"),
        ("4", "Mẹ"),
        ("5", "Anh"),
        ("6", "Chị"),
        ("7", "Em"),
        ("8", "Cô"),
        ("9", "Dì"),
        ("10", "Chú"),
        ("11", "Bác"),
    ]
# thong tin nguoi dung
class Personal(models.Model):
    ten = models.CharField(max_length=50, null=True)
    namsinh = models.DateField()
    gioitinh = models.CharField(max_length=10)
    sdt = models.CharField(max_length=15)
    email = models.EmailField(max_length=50, null=True)
    thebh = models.CharField(max_length=50)
    anh = models.ImageField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True, blank=True)
    # gioitinh = models.CharField(blank=True, choices=gt_type.choices, max_length=10)
    qhe = models.CharField(max_length=2, choices=SHIRT_SIZES)

    def __str__(self):
        return self.ten
    @property
    def ImageURL(self):
        try:
            url = self.anh.url
        except:
            url = ''
        return url


# benh
class Disease(models.Model):
    # ma_benh = models.CharField(max_length=20)
    ten_benh = models.CharField(max_length=30)

    def __str__(self):
        return self.ten_benh


# thuoc
class Medicine(models.Model):
    ten_goc = models.CharField(max_length=30, null=False)
    ten_bd = models.CharField(max_length=30)
    gia = models.FloatField()

    # def __init__(self, ten_goc, ten_bd):
    #     self.ten_goc = ten_goc
    #     self.ten_bd = ten_bd
    def __str__(self):
        return f"{self.ten_goc} ({self.ten_bd}) "

# toa thuoc
# class Prescription(models.Model):
#     ten_bs = models.CharField(max_length=50)
#     anh = models.ImageField(null=True, blank=True)
#     ngay = models.DateField()

#     def __str__(self):
#         return str(self.id)

# thong tin suc khoe, toa thuoc
class Health(models.Model):
    ma_canhan = models.ForeignKey(Personal, on_delete=models.SET_NULL, null=True, blank=False)
    ma_benh = models.ForeignKey(Disease,on_delete=models.SET_NULL, null=True, blank=False)
    # ma_toa = models.ForeignKey(Prescription, on_delete=models.SET_NULL, null=True, blank=False)
    ngay = models.DateField()
    diachi = models.TextField(max_length=50)
    tenbs = models.CharField(null=True, max_length=30)
    anh = models.ImageField(null=True, blank=True)

    def __str__(self):
        return str(self.id)
    
# chi tiet toa thuoc
class Pre_Details(models.Model):
    ma_toa = models.ForeignKey(Health, on_delete=models.SET_NULL, null=True, blank=False)
    ma_thuoc = models.ForeignKey(Medicine, on_delete=models.SET_NULL, null=True, blank=False)
    lieuluong = models.IntegerField()

    def __str__(self):
        return str(self.id)
    
class Disease_Vac(models.Model):
    # ma_benh = models.CharField(max_length=20)
    ten_benh = models.CharField(max_length=30)

    def __str__(self):
        return self.ten_benh
    
class Vaccination(models.Model):
    canhan = models.ForeignKey(Personal, on_delete=models.SET_NULL, null=True, blank=False)
    ten_vac = models.CharField(max_length=100)
    ten_benh = models.ForeignKey(Disease_Vac, on_delete=models.SET_NULL, null=True, blank=False)
    phan_ung = models.CharField(max_length=100)
    ngay_tiem = models.DateField()
    ngay_hen = models.DateField(null=True, blank=False)
    dia_chi = models.TextField(max_length=200)
    
    def __str__(self):
        return str(self.id)

home/views.py
from telnetlib import LOGOUT
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from .models import *
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .forms import *
from django.contrib.auth.models import User, auth
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.db.models import Q
from django.views.generic import TemplateView, ListView

from django.core.mail import send_mail
from django.conf import settings
import datetime

# Create your views here.
def register(request):
    if request.method == 'POST':
        # first_name = request.POST['first_name']
        # last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password==confirm_password:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'Tên người này đã được sử dụng')
                return redirect(register)
            # elif User.objects.filter(email=email).exists():
            #     messages.info(request, 'Email này đã được sử dụng')
            #     return redirect(register)
            else:
                user = User.objects.create_user(username=username,email=email, password=password
                                         )
                user.save()
                
                return redirect('login')


        else:
            messages.info(request, 'Cả hai mật khẩu đều không khớp')
            return redirect(register)
            

    else:
        return render(request, 'register.html')
    
def login_user(request):
    # if request.user.is_authenticated:
    #     return redirect('home')
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.info(request, 'Tên hoặc mật khẩu không đúng')
            return redirect('login')

    else:
        return render(request, 'login.html')
# chưa sd  
def change_mk(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, _('Your password was successfully updated!'))
            return redirect('accounts:change_password')
        else:
            messages.error(request, _('Please correct the error below.'))
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'change_mk.html', {
        'form': form
    })

def logout_user(request):
    logout(request)
    return redirect('home')

def home(request):
    if request.user.is_authenticated:
        personals = Personal.objects.filter(user=request.user.id).order_by('-namsinh')
        
        context = {'personals':personals}
    
        return render(request, 'home.html', context)
    else:
        return redirect('login')


def tk(request):
    if request.user.is_authenticated:
        
        if request.method == "POST":
            personals = Personal.objects.filter(user=request.user.id).order_by('-namsinh')
            tk_ed = request.POST["tk_ed"]
            tieude=request.POST.get('tieude')
            if tieude=='1':
                benh=Disease.objects.filter(ten_benh__icontains = tk_ed)
                for k in benh:
                    # health=Health.objects.get(ma_benh=k, ma_canhan=personals)
                
                    health = Health.objects.filter(ma_canhan__id__in=personals, ma_benh=k)
                    # key.append({'ma_canhan': h.ma_canhan})
                    t='Bệnh'
                    return render(request, 'tk.html',{"tk_ed":tk_ed, "health":health, 'tieude':t})
            
            elif tieude=='3':
                t='Tên Cá nhân'
                ten=Personal.objects.filter(ten__icontains = tk_ed, user=request.user.id)
                health=Health.objects.filter(ma_canhan__in=ten.all())
                return render(request, 'tk.html',{"tk_ed":tk_ed, "health":health, 'tieude':t})
            
            elif tieude=='2':
                t='Thuốc'
                thuoc=Medicine.objects.filter(ten_goc__icontains = tk_ed)
                pre=Pre_Details.objects.filter(ma_thuoc__in=thuoc).values('ma_toa')
                # pre=Pre_Details.objects.filter(ma___in__ma_toa=thuoc)
                health = Health.objects.filter(id__in=pre.all())
            
                return render(request, 'tk.html',{"tk_ed":tk_ed, "health":health, "tieude":t})
        
            elif tieude=='4':
                # ten=Personal.objects.filter(user=request.user.id).values('ten')
                vac=Vaccination.objects.filter(ten_vac__icontains = tk_ed).values('canhan')
                for i in vac:
                    t='Tên Vắc xin'
                    # đang lỗi
                    ten1=Personal.objects.filter(user=request.user.id, ten=i).values('ten')
                    health=Health.objects.filter(ma_canhan__in=vac.all())
                    return render(request, 'tk.html',{"tk_ed":tk_ed, "health":health, 'tieude':t})
                  
            else:
                return redirect(home) 
        else:
            return redirect(home)  
    else:
        return redirect('login')   

    # return render(request, 'tk.html',{"tk_ed":tk_ed, "health":health})

    # if request.method == "POST":
    #     tk_ed = request.POST["tk_ed"]
    #     keys = Disease.objects.filter(ten_benh__icontains = tk_ed)
        
    #     health = []
    #     for k in keys:
    #         health=Health.objects.filter(ma_benh=k)
    #         # key.append({'ma_canhan': h.ma_canhan})

    # return render(request, 'tk.html',{"tk_ed":tk_ed, "health":health})


def add_tn(request):
    # form = PesonalForm()
    # if request.method == "POST":
    #     form = PesonalForm(request.POST, request.FILES)
    #     if form.is_valid():
    #         form.save()
    #         return HttpResponseRedirect('/')
    # # anh = Personal.objects.all()
    # return render(request, 'add_tn.html', context={'form':form})
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = PesonalForm(request.POST or None, request.FILES)

            if form.is_valid():
                data = form.save()
                data.user = request.user
                data.save()
                return redirect(home)
            
        else:
            form = PesonalForm()
        return render(request,'add_tn.html', {'form':form})
    return redirect(login_user)
  
def edit_tn(request,id):
    if request.user.is_authenticated:
        produ = Personal.objects.get(id=id)
        if request.method == 'POST':
            form = PesonalForm(request.POST or None, request.FILES, instance=produ)
    
            if form.is_valid():
                data = form.save()
                data.user = request.user
                data.save()
                # img_obj = form.instance
                # return render(request, 'add_tn.html', {'form': form, 'img_obj': img_obj})
                return redirect(home)
        else:
            form = PesonalForm(instance=produ)
            return render(request,'add_tn.html',{"form":form})
    return redirect(login_user)

def delete_tn(request,id):
	if request.user.is_authenticated:
            produ = Personal.objects.get(id=id)
            produ.delete()
            return redirect(home)


def health(request,id):
    # if request.user.is_authenticated:
    #     personal = request.user.personal
    #     health, created = Health.objects.get_or_create(personal = personal, complex= False)
    # else:
    # if request.user.is_authenticated:
        # id = request.GET.get(id=id)
        healths = Health.objects.filter(ma_canhan=id)

        context = {'healths': healths, 'id':id}
        return render(request, 'health.html', context)

def detail_health(request,id):
    if request.user.is_authenticated:
        # idd = request.GET.get('id','')
        healths = Health.objects.filter(id=id)
        pre_details= Pre_Details.objects.filter(ma_toa=id)
        he = Health.objects.get(id=id)

        if request.method == 'POST':
            me = MedicineForm(request.POST or None)
            if me.is_valid():
                mee = me.save()
                mee.ma_toa=he
                mee.save()
                return redirect(detail_health,id)
        else:
            me = MedicineForm()

        context = {'healths': healths, 'pre_details': pre_details, 'me':me}
        return render(request, 'detail_health.html', context)


def add_health(request,id):
    if request.user.is_authenticated:
        per = Personal.objects.get(id=id)
        # pre = Pre_Details.objects.get(ma_toa=per.id)
        if request.method == 'POST':
            form = HealthForm(request.POST or None)
    
            if form.is_valid():
                data = form.save()
                data.ma_canhan = per
                data.save()
                return redirect(health,id)
        else:
            form = HealthForm()
        return render(request, 'add_health.html', {'form' : form})


def edit_health(request,id_per,id_health):
    if request.user.is_authenticated:
        per = Personal.objects.get(id=id_per)
        hea = Health.objects.get(ma_canhan=per, id = id_health)
        if request.method == 'POST':
            form = HealthForm(request.POST or None, request.FILES, instance=hea)

            if form.is_valid():
                data = form.save()

home/templates/add_benh.html
{% extends "base.html" %}
{% load static %}
{% block main_content %} 
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <div class="container">
          <div class="card mt-4">
            <div class="card-body">
            <table class="table table-striped">
              <thead class="thead-dark">
                <form class="d-flex" method="post" enctype= "multipart/form-data" action = "{% url 'add_benh' %}" >
                    {% csrf_token %}
                        <label for="inputPassword4" class="fs-4"><b>Thêm tên bệnh</b></label>

                        <div class="input-group mb-3">
                            <input type="text" name="tenbenh" class="form-control" placeholder="Tên bệnh" aria-label="tên bệnh" aria-describedby="button-addon2">
                            <button class="btn btn-primary" type="submit" id="button-addon2">Thêm</button>
                          </div>
                  </form>
                  <tr>
                    <th scope="col" class="fs-4">Tên bệnh</th>

                    
                  </tr>
                </thead>
                <tbody>
                  {% if user.is_authenticated %}
                  {%for b in benh %}
                  <tr>
                    <th>{{b.ten_benh}}</th>
                  </tr>
                  {% endfor %}
                  {% endif %}
                </nav>
                
              </table>
            </div></div></div>
      
        <script src="" async defer></script>
    </body>
</html>
{% endblock main_content %}

home/templates/add_benhtiem.html
{% extends "base.html" %}
{% load static %}
{% block main_content %} 
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <div class="container">
          <div class="card mt-4">
            <div class="card-body">
            <table class="table table-striped">
              <thead class="thead-dark">
                <form class="d-flex" method="post" enctype= "multipart/form-data" action = "{% url 'add_benhtiem' %}" >
                    {% csrf_token %}
                        <label for="inputPassword4" class="fs-4"><b>Thêm các bệnh có thể phòng ngừa bằng vắc-xin</b></label>

                        <div class="input-group mb-3">
                            <input type="text" name="tenbenh" class="form-control" placeholder="Tên bệnh" aria-label="tên bệnh" aria-describedby="button-addon2">
                            <button class="btn btn-primary" type="submit" id="button-addon2">Thêm</button>
                          </div>
                  </form>
                  <tr>
                    <th scope="col" class="fs-4">Tên bệnh</th>

                    
                  </tr>
                </thead>
                <tbody>
                  {% if user.is_authenticated %}
                  {%for b in benh %}
                  <tr>
                    <th>{{b.ten_benh}}</th>
                  </tr>
                  {% endfor %}
                  {% endif %}
                </nav>
                
              </table>
            </div></div></div>
      
        <script src="" async defer></script>
    </body>
</html>
{% endblock main_content %}

home/templates/add_health.html
{% extends "base.html" %}
{% load static %}
{% block main_content %} 
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">

        

    </head>
    <body>
        <div class="container">
          <div class="card mt-4">
            <div class="card-body">
            <div class ="row justify-content-around">
              <h3 class="text-center" scope="col">Thêm thông tin về lần khám </h3>

            <form class="row g-3" method="post" enctype= "multipart/form-data" >
              {% csrf_token %}
                
              <table class="table table-borderless">
                <thead class="thead-dark">
                    <tr>
                      <th scope="col" class="fs-3">Thông tin</th>
                      <th scope="col" class="fs-3">Thêm</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% if user.is_authenticated %}
                    <tr>
                      <th scope="row">Tên bệnh</th>
                      <td>
                        <div class="input-group mb-3">
                            {{form.ma_benh}}
                        </div>
                      </td>
                    
                    </tr>
                    <tr>
                      <th scope="row">Địa chỉ khám</th>
                      <td>
                        <div class="input-group mb-3">
                          {{form.diachi}}
                        </div>
                      </td>
    
                    </tr>
                    <tr>
                      <th scope="row">Ngày khám</th>
                      <td>
                        <div class="input-group mb-3">
                          {{form.ngay}}
                        </div>
                      </td>
    
                    </tr>
                    <tr>
                      <th scope="row">Tên bác sĩ</th>
                      <td>
                        <div class="input-group mb-3">
                          {{form.tenbs}}
                        </div>
                      </td>
    
                    </tr>
                  
                    <tr>
                      <th scope="row">Ảnh toa thuốc</th>
                      <td>
                        <div class="input-group mb-3">
                          {{form.anh}}
                        </div>
                      </td>
    
                    </tr>
    
                    {% endif %}
                  </nav>
                  
                </table>
    
                <div class="text-center ">
                  <button type="submit" class="btn btn-primary">Thêm</button>
                </div>
    
      </form></div></div></div></div>
    </body>
</html>
{% endblock main_content %}

home/templates/add_thuoc.html
{% extends "base.html" %}
{% load static %}
{% block main_content %} 

{%for health in healths %}
<div class="container">
<h3 scope="col">Họ và Tên: <td>{{health.ma_canhan}}</td></h3>
<h5 scope="col">Năm sinh: {{health.ma_canhan.namsinh|date:"d-m-Y"}}</h5>
<h5 scope="col">Giới Tính: {{health.ma_canhan.gioitinh}}</h5>
<h5 scope="col">Số điện thoại: {{health.ma_canhan.sdt}}</h5>
<h5 scope="col">Số thẻ bảo hiểm: {{health.ma_canhan.thebh}}</h5>
<h5 scope="col">Chuẩn đoán: {{health.ma_benh.ten_benh}}</h5>
<h5 scope="col">Tên bác sĩ: {{health.tenbs}}</h5>
<h3 class="text-center" scope="col">Chỉ định dùng thuốc</h3>
<form class="row g-3" method="post" enctype= "multipart/form-data" >
  {% csrf_token %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Tên gốc</th>
        <th scope="col">Tên biệt dược</th>
        <th scope="col">Liều lượng (lần/ngày)</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row"></th>
        <td>{{me.ma_thuoc}}</td>
        <td>{{me.lieuluong}}</td>
      </tr>
      {% endfor %}
      <div class="text-center ">
        <button type="submit" class="btn btn-primary">Thêm</button>
      </div>
    </tbody>
  </table>
</form>
</div>
{% endblock main_content %}

home/templates/health.html
{% extends "base.html" %}
{% load static %}
{% block main_content %} 
<div class="container">
  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Ngày khám</th>
        <th scope="col">Địa chỉ</th>
        <th scope="col">Tên Bệnh</th>
        <th><th><a class="btn btn-success" href="{% url 'add_health' id %}">Thêm</a></th></th>
      </tr>
    </thead>
    <tbody>
      {%for health in healths %}
      <tr>
        <th>{{health.ngay|date:"d-m-Y"}}</th>
        <td>{{health.diachi}}</td>
        
        <td>{{health.ma_benh.ten_benh}}</td>
        <td><a class="btn btn-success" href="{% url 'detail_health' health.id %}">Chi tiết</a></td>
        <td><a class="btn btn-success" href="{% url 'edit_health' id health.id %}">Sửa thông tin</a></td>
        <td><a class="btn btn-success" style="background-color: #FF0000;" href="{% url 'delete_health' id health.id %}">Xóa</a></td>
      </tr>
      {% endfor %}
      
    </tbody>
  </table>
</div>
{% endblock main_content %}

home/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block main_content %} 
<div class="container">
<table class="table table-striped">
  <thead class="thead-dark">
      <tr>
        <th scope="col">id</th>
        <th scope="col">Ảnh</th>
        <th scope="col">Name</th>
        <th scope="col">Ngày sinh</th>
        <th scope="col">Giới tính</th>
        <th scope="col">Quan hệ</th>
        <th><a class="btn btn-success" href="{% url 'add_tn' %}">Thêm</a></th>
      </tr>
    </thead>
    <tbody>
      {% if user.is_authenticated %}
      {%for personal in personals %}
      <tr>
        <th scope="row">{{personal.id}}</th>
        <td><img class="img" src="{{personal.ImageURL}}" width="100" height="100" ></td>
        <td>{{personal.ten}}</td>
        <td>{{personal.namsinh|date:"d-m-Y"}}</td>
        <td>{{personal.gioitinh}}</td>
        <td>{{personal.get_qhe_display}}</td>
        <td><a class="btn btn-success" href="{% url 'health' personal.id %}">Những lần khám</a></td>
        <td><a class="btn btn-success" href="{% url 'edit_tn' personal.id %}">Sửa thông tin</a></td>
        <td><a class="btn btn-success" style="background-color: #FF0000;" href="{% url 'delete_tn' personal.id %}">Xóa</a></td>
        
      </tr>
      {% endfor %}
      {% endif %}
    </nav>
    
  </table>
</div>
{% endblock main_content %}

home/templates/tk.html
{% extends "base.html" %}
{% load static %}
{% block main_content %} 
<h3 class="text-center" scope="col">Kết quả tìm kiếm {{tieude}}: {{tk_ed}}</h3>
<div class="container">
  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Mối quan hệ</th>
        <th scope="col">Tên cá nhân</th>
        <th scope="col">Địa chỉ Khám</th>
        <th scope="col">Tên Bệnh</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {%for h in health %}
      <tr>
        <th>{{h.ma_canhan.get_qhe_display}}</th>
        <th>{{h.ma_canhan.ten}}</th>
        <td>{{h.diachi}}</td>
        <td>{{h.ma_benh.ten_benh}}</td>
        <td><a class="btn btn-success" href="{% url 'detail_health' h.id %}">Chi tiết</a></td>
        
      </tr>
      {% endfor %}
      
    </tbody>
  </table>
</div>
{% endblock main_content %}

home/templates/tk_benh.html
{% extends "base.html" %}
{% load static %}
{% block main_content %} 
<div class="container">
  <div class="card mt-5">
    <div class="card-body">
        <form class="row g-3" method="POST" action = "{% url 'tk_benh' %}" enctype= "multipart/form-data" >
          {% csrf_token %}
            
          <table class="table table-borderless">
            
              <tbody>
                <tr>
                  <th scope="row"><label class="form-label fs-5"><b>Khoảng Thời gian</b></label></th>
                  <td>
                    <input type="date" class="form-control" name="ngaybd">
                  </td>
                  <td>
                    <input type="date" class="form-control" name="ngaykt">
                  </td>
                
                </tr>
                {% comment %} <tr>
                  <th scope="row"><label class="form-label fs-5"><b>Nhóm</b></label></th>
                  <td>
                    <select name="tieude" class="form-select">
                      <option  value="1">Bệnh</option>
                      <option  value="2">Tiêm ngừa</option>
                    </select>
                  </td>
                </tr> {% endcomment %}

              
              </nav>
              
          </table>
          <center  class="col-12">
            <button type="submit" class="btn btn-primary">Thống kê</button>
          </center>
        </form>
      </div></div></div>


    <h3 class="text-center mt-5" scope="col">Kết quả thống kế từ {{ngaybd}} đến {{ngaykt}}</h3>
    <div class="container">
      <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Mối quan hệ</th>
            <th scope="col">Tên cá nhân</th>
            <th scope="col">Địa chỉ Khám</th>
            <th scope="col">Tên Bệnh</th>
            <th scope="col">Ngày khám bệnh</th>
          </tr>
        </thead>
        <tbody>
          {%for h in health %}
          <tr>
            <td>{{h.ma_canhan.get_qhe_display}}</td>
            <th>{{h.ma_canhan.ten}}</th>
            <td>{{h.diachi}}</td>
            <td>{{h.ma_benh.ten_benh}}</td>
            <th>{{h.ngay|date:"d-m-Y"}}</th>
            <td><a class="btn btn-success" href="{% url 'detail_health' h.id %}">Chi tiết</a></td>
            
            
          </tr>
          {% endfor %}
          
        </tbody>
      </table>
    </div>
{% endblock main_content %}